name = "uart_master_slave"
description = "Shiny new project"
version = "0.0.0"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]

executables = ["uart_master_slave"]

[gpr-set-externals]
#  I want all dependencies with full debug information
ATOMIC_BUILD_MODE="debug"
BBQUEUE_BUILD_MODE="debug"
CORTEXM_BUILD_MODE="debug"
ITSYBITSY_RP2040_BSP_BUILD_MODE="debug"
PICO_BSP_BUILD_MODE="debug"
RP2040_HAL_BUILD_MODE="debug"
TINY_RP2040_BSP_BUILD_MODE="debug"
USB_EMBEDDED_BUILD_MODE="debug"

[[depends-on]]  # Added by alr
gnat_arm_elf = "^11.2.3"  # Added by alr
[[depends-on]]  # Added by alr
pico_bsp = "^1.3.0"  # Added by alr
[[depends-on]]  # Added by alr
itsybitsy_rp2040_bsp = "~0.1.0"  # Added by alr
[[depends-on]]  # Added by alr
rp2040_hal = "^1.3"  # Added by alr
[[pins]]  # Added by alr
rp2040_hal = { path='../../rp2040_hal' }   # Added by alr
